INSERT INTO dbo.Quotes (Title, Author, Description , Type)
VALUES ( 'Action','Walt Disney' ,'The way to get started is to quit talking and begin doing.' ,'Motivation'),
 ( 'Action','Nelson Mandela' ,'The greatest glory in living lies not in never falling, but in rising every time we fall.' ,'Inspiration'),
 ( 'Life','Eleanor Roosevelt' ,'If life were predictable it would cease to be life, and be without flavor..' ,'Life'),
 ( 'Action','John Lennon' ,'Life is what happens when you are busy making other plans.' ,'Motivation')



/*
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJlTUpBeUpfWExCU0dkeEdiUGRHWSJ9.eyJpc3MiOiJodHRwczovL3F1b3RlYXBpc29va2NoYW5kLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MDE3ZjliYTUyMzhmYjAwNjk2MzM3ZDIiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxLyIsImlhdCI6MTYxMjI1MDgyMSwiZXhwIjoxNjEyMzM3MjIxLCJhenAiOiJFbzF5R0Vkc243WkhNZ3lsQ1VYZlA3cFJBOG9GbXNuTyIsImd0eSI6InBhc3N3b3JkIn0.Mao4qfOz_uFKcpimssqxQUPi5lktajnTbEdkFiw5peuNztqJ2tonQE8SIa7K_hOOGSa4Q_RVo3Rf83ukhjg4xhE78E91Dg2e9j0LJ4EcUdo2JaIEZmU9wuZBajXC0aGkNvg99lmeFbkBPSPrjmk8ILgWYNmt7sq4QHh7bwaDmReW9gx8bWbFoExb6i0RrPduxkiZgcat_aLz_k2QZdVF25Kb-pmJryXM3zAaKhS3NcW0su8unP-zthWjOyttoAp8RmzGfpAPilIJR2usJvhb9WhcLQlGPz1xs9lzh7Kdjm1BiFK2NVVbU2L3xHGSKk63htpFRdfvg0YDM6YqE-yo0g


eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJlTUpBeUpfWExCU0dkeEdiUGRHWSJ9.eyJpc3MiOiJodHRwczovL3F1b3RlYXBpc29va2NoYW5kLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MDE4MGFiYmNlMjU4OTAwNzE5OWM0NzciLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxLyIsImlhdCI6MTYxMjI1NDg4NiwiZXhwIjoxNjEyMzQxMjg2LCJhenAiOiJFbzF5R0Vkc243WkhNZ3lsQ1VYZlA3cFJBOG9GbXNuTyIsImd0eSI6InBhc3N3b3JkIn0.GvsBJDq2kyqsu9zOkj7ypGZNXQUguSiyP71Ai-BZ8EPXqJumo4lVrhkOOCbBnnBwfpb_XLPvLISAkdwhGr6P9GRGRUvRIuKkXVa_sa_bBdWr7tIh5XUdFzCftApk5g-zGKq_LGla1qMedBksWWHegai9JpVsgEJU9i_UfvVaZX7gxwG7CdjnaocIZ4s_Te_xcVu8t6Rw01OC5UFMUcUVLlQ4JLbUZIju-phby7kgII_hjJPy08sODo5o4pb8AiJMH_iUOQF1VzwSgxRuM18n6D5ut6YJY7nXQ4XlV3FkuI9ShoGQr_EKefeYsxL4O9dXHAzJdD1VZxABtaybftTDYw

*/